global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['localhost:3005']  
