
services:
  prometheus:
    image: prom/prometheus
    ports:
       - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
       - "3001:3000"

